// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBe55YrEm1D_AS3UmFgPbbCUG84qmJFJCc',
    appId: '1:943592320:web:cee68e35e1b4e3fde7e765',
    messagingSenderId: '943592320',
    projectId: 'acarpool-lite-bc318',
    authDomain: 'acarpool-lite-bc318.firebaseapp.com',
    storageBucket: 'acarpool-lite-bc318.firebasestorage.app',
    measurementId: 'G-2D4GNKGSRB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBc7k591-hNWt_rZK1ffAEjY9UEAagJR5s',
    appId: '1:943592320:android:1527c6da26848ddee7e765',
    messagingSenderId: '943592320',
    projectId: 'acarpool-lite-bc318',
    storageBucket: 'acarpool-lite-bc318.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzkhxy86zeEIK-v10OwYjolmdKMGiTLYI',
    appId: '1:943592320:ios:5ab99ebf38b4c485e7e765',
    messagingSenderId: '943592320',
    projectId: 'acarpool-lite-bc318',
    storageBucket: 'acarpool-lite-bc318.firebasestorage.app',
    iosBundleId: 'com.example.repoAksomdaGroupe27CarpoolLite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzkhxy86zeEIK-v10OwYjolmdKMGiTLYI',
    appId: '1:943592320:ios:5ab99ebf38b4c485e7e765',
    messagingSenderId: '943592320',
    projectId: 'acarpool-lite-bc318',
    storageBucket: 'acarpool-lite-bc318.firebasestorage.app',
    iosBundleId: 'com.example.repoAksomdaGroupe27CarpoolLite',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBe55YrEm1D_AS3UmFgPbbCUG84qmJFJCc',
    appId: '1:943592320:web:cbbed3c9fc7609c4e7e765',
    messagingSenderId: '943592320',
    projectId: 'acarpool-lite-bc318',
    authDomain: 'acarpool-lite-bc318.firebaseapp.com',
    storageBucket: 'acarpool-lite-bc318.firebasestorage.app',
    measurementId: 'G-MH386YHC71',
  );
}
