// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRyOugGyyWBdQ4EmJ-BfbkbPavoo-_LK0',
    appId: '1:408768248556:web:e936d68154f97264c443c9',
    messagingSenderId: '408768248556',
    projectId: 'carpool-lite',
    authDomain: 'carpool-lite.firebaseapp.com',
    storageBucket: 'carpool-lite.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArmG7ZwlcMh4UL7vBJKYGRhG5njzBhGWM',
    appId: '1:408768248556:android:dc1d24ef2b6a06d3c443c9',
    messagingSenderId: '408768248556',
    projectId: 'carpool-lite',
    storageBucket: 'carpool-lite.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDli8gehYJTivvqTekpCsT2cv5HSmyJ57c',
    appId: '1:408768248556:ios:1526f05a9837d114c443c9',
    messagingSenderId: '408768248556',
    projectId: 'carpool-lite',
    storageBucket: 'carpool-lite.firebasestorage.app',
    iosBundleId: 'com.example.carpoolLite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDli8gehYJTivvqTekpCsT2cv5HSmyJ57c',
    appId: '1:408768248556:ios:1526f05a9837d114c443c9',
    messagingSenderId: '408768248556',
    projectId: 'carpool-lite',
    storageBucket: 'carpool-lite.firebasestorage.app',
    iosBundleId: 'com.example.carpoolLite',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRyOugGyyWBdQ4EmJ-BfbkbPavoo-_LK0',
    appId: '1:408768248556:web:3e2488a8d8d1e2e5c443c9',
    messagingSenderId: '408768248556',
    projectId: 'carpool-lite',
    authDomain: 'carpool-lite.firebaseapp.com',
    storageBucket: 'carpool-lite.firebasestorage.app',
  );
}
