// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
//
// Configuration du projet Firebase « carpoollite » (254475674559).
// Les identifiants d'applications proviennent de firebase.json et la clé
// publique est celle affichée dans la console Firebase du projet.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiHW6af5NqVD9bKI-tALb7_HO0N99xVvQ',
    appId: '1:254475674559:web:d30736e7230d291ac4370a',
    messagingSenderId: '254475674559',
    projectId: 'carpoollite',
    authDomain: 'carpoollite.firebaseapp.com',
    storageBucket: 'carpoollite.firebasestorage.app',
    measurementId: 'G-C6MYCFG5GM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiHW6af5NqVD9bKI-tALb7_HO0N99xVvQ',
    appId: '1:254475674559:android:bf4f937024649afac4370a',
    messagingSenderId: '254475674559',
    projectId: 'carpoollite',
    storageBucket: 'carpoollite.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiHW6af5NqVD9bKI-tALb7_HO0N99xVvQ',
    appId: '1:254475674559:ios:719b5cbf892bd478c4370a',
    messagingSenderId: '254475674559',
    projectId: 'carpoollite',
    storageBucket: 'carpoollite.firebasestorage.app',
    iosBundleId: 'com.example.repoAksomdaGroupe27CarpoolLite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiHW6af5NqVD9bKI-tALb7_HO0N99xVvQ',
    appId: '1:254475674559:ios:719b5cbf892bd478c4370a',
    messagingSenderId: '254475674559',
    projectId: 'carpoollite',
    storageBucket: 'carpoollite.firebasestorage.app',
    iosBundleId: 'com.example.repoAksomdaGroupe27CarpoolLite',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBiHW6af5NqVD9bKI-tALb7_HO0N99xVvQ',
    appId: '1:254475674559:web:b834202f8b620aebc4370a',
    messagingSenderId: '254475674559',
    projectId: 'carpoollite',
    authDomain: 'carpoollite.firebaseapp.com',
    storageBucket: 'carpoollite.firebasestorage.app',
  );
}
